### ISSUE TITLE
"Allowed schemas" considered harmful

### ISSUE THREAD

**Issue by smithtim** [rkaippully/scim-patch#8]
I just spent a long time debugging an issue where my patch was not returning an error, but also not applying the patch.  It was just returning the same object, unchanged.

It turned out there was a mistake in the path.  Normally this would have returned an `Invalid path` error.  But because my schema contained the "allowed schemas" flag `:schemas`, it simply ignored the invalid path.

I think this kind of mistake will be common enough that the "allowed schemas" feature is going to cause more trouble than it is worth.  Can it be removed from the patch library?

Thanks for all your work on this library!

**Comment by rkaippully** [comment]
The original usecase for #6 was for the case when an end-user submits a patch that touches attributes that belong to multiple systems but your system handles only a subset of them. The rest of the schemas are probably handled by a different system and you don't want the patch operation to fail in your system.

I think having this option is still useful but I can understand how this would be surprising/unexpected. May be this should be made explicit in the API? Probably, `scim-patch.core/patch` can take an `options` parameter with `{:skip-unknown-schemas true}` that determines whether patches on these schemas are ignored.
